#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Unit tests for FlatInt matching.TopicBased algorithm
"""

import pytest

def test_sub_collection(SubFixture):
    Sub = SubFixture.Sub
    Event = SubFixture.Event
    events = SubFixture.events
    subs = SubFixture.subs
    expected_interest = SubFixture.expected_interest
    assert SubFixture.subscriptions >= 2, "must have at least 6"

    divider = len(
    
    subs1 = SubFixture.subscriptions
    subs2
    Sub.Collection
